FROM armck/ubuntu:24.04-dev

ARG JDK_VERSION=21

# avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /tmp/container \
    && cd /tmp/container \
    # primary installs
    && apt update && apt -y install \
        openjdk-${JDK_VERSION}-jdk  \
    # cleanup
    && apt autoremove -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/container

# switch back to dialog for any ad-hoc use of apt
ENV DEBIAN_FRONTEND=dialog

# supports multi-arch
