FROM armck/ubuntu:24.04-dev

ARG DOTNET_VERSION=8.0

# avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /tmp/container \
    && cd /tmp/container \
    # primary installs
    && apt update && apt -y install \
        dotnet-sdk-${DOTNET_VERSION}  \
    # cleanup
    && apt autoremove -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/container

# switch back to dialog for any ad-hoc use of apt
ENV DEBIAN_FRONTEND=dialog
