# scope: Build and Push Release Docker Images
name: wf-docker-push-release

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile**'
      - '.github/workflows/docker-push-release.yaml'
      - '.github/workflows/scripts/**'

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  get-builds:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      build_matrix_ubuntu: ${{ steps.set-build-matrices.outputs.build_matrix_ubuntu }}
      build_matrix_go: ${{ steps.set-build-matrices.outputs.build_matrix_go }}
      build_matrix_python: ${{ steps.set-build-matrices.outputs.build_matrix_python }}
      build_matrix_terraform: ${{ steps.set-build-matrices.outputs.build_matrix_terraform }}
      build_matrix_java: ${{ steps.set-build-matrices.outputs.build_matrix_java }}
      build_matrix_dotnet: ${{ steps.set-build-matrices.outputs.build_matrix_dotnet }}
      build_matrix_terraform_azure: ${{ steps.set-build-matrices.outputs.build_matrix_terraform_azure }}
      build_matrix_pyspark: ${{ steps.set-build-matrices.outputs.build_matrix_pyspark }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Change Files
        id: change-files
        uses: jitterbit/get-changed-files@v1

      - name: Set Build Matrices
        id: set-build-matrices
        env:
          CHANGED_FILES: ${{ steps.change-files.outputs.added_modified }}
        run: bash .github/workflows/scripts/set-build-matrices.sh

  build-ubuntu:
    needs: [get-builds]
    if: ${{ needs.get-builds.outputs.build_matrix_ubuntu != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_ubuntu).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-go:
    needs: [get-builds, build-ubuntu]
    if: ${{ needs.get-builds.outputs.build_matrix_go != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_go).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-python:
    needs: [get-builds, build-ubuntu]
    if: ${{ needs.get-builds.outputs.build_matrix_python != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_python).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-terraform:
    needs: [get-builds, build-ubuntu]
    if: ${{ needs.get-builds.outputs.build_matrix_terraform != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_terraform).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64


  build-java:
    needs: [get-builds, build-ubuntu]
    if: ${{ needs.get-builds.outputs.build_matrix_java != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_java).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-dotnet:
    needs: [get-builds, build-ubuntu]
    if: ${{ needs.get-builds.outputs.build_matrix_dotnet != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_dotnet).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-terraform-azure:
    needs: [get-builds, build-terraform]
    if: ${{ needs.get-builds.outputs.build_matrix_terraform_azure != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_terraform_azure).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64

  build-pyspark:
    needs: [get-builds, build-python]
    if: ${{ needs.get-builds.outputs.build_matrix_pyspark != '{"include":[]}' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-builds.outputs.build_matrix_pyspark).include }}
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    secrets: inherit
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
      image_tag: ${{ matrix.image_tag }}
      platforms: linux/amd64,linux/arm64
